### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by scd31** [Turbo87/aprs-parser-rs#46]
Would you have any interest in having an additional maintainer (me)? This is a great library and I think Rust has a future in ham radio once the libraries get there. I would love to maintain it and get it a little closer to parity with the APRS standard.

**Comment by scd31** [comment]
@Turbo87 Sorry to ping but did you have a chance to look at this? I have a lot of ideas for the future of this project and I'd love to have the opportunity to implement some of them!

**Comment by Turbo87** [comment]
just invited you. I'll see if I can get you crates.io access too.

**Comment by scd31** [comment]
Thank you very much! It's greatly appreciated!
