### ISSUE TITLE
Support Mic-E data

### ISSUE THREAD

**Issue by scd31** [Turbo87/aprs-parser-rs#61]
I would like to implement decoding/encoding Mic-E data. I need some feedback into how the data structure should look.

For context, Mic-E data does not have a destination callsign. Instead, certain bits are stuffed into the destination callsign field. This contrasts the current data structure, which assumes all packets have a destination.

To fix this, I'm thinking:

- Remove the `to` field from `AprsPacket`
- Add a `to` field to `AprsPosition`, `AprsMessage`, and `AprsData::Unknown` (and create a corresponding struct for `AprsData::Unknown`)
- Add a new `AprsData::MicE` variant (and corresponding struct) without a `to` field
- Add a helper method on `AprsPacket` which will retrieve the `to` field from the inner struct (returning an `Option<Callsign>`)

@benjamin-l Do you have any thoughts on this?

**Comment by olivia-fl** [comment]
Yeah, that approach seems pretty reasonable to me.

The main disadvantages I can see is that the current design allows users to construct and manipulate `AprsPosition` and `AprsMessage` structs without knowing the destination ahead-of-time. I could see the new requirement (that the destination must be passed to construct a position or message) complicating some use-cases.

For example, a function like the following would be simple to use and implement with the current API, but ugly with the new one:

```rust
fn send_to_all(data: AprsData, to: &[Callsign]) -> impl Iterator<Item = AprsPacket> { ... }
```

The other minor disadvantage is that there's no way to represent unknown data without a position specified.

---

A design that avoids these disadvantages, in exchange for a more complex API:

```rust
enum AprsData {
    WithDestination {
        to: Callsign,
        data: AprsDataWithDestination
    },
    WithoutDestination {
        data: AprsDataWithoutDestination
    },
}

enum AprsDataWithoutDestination {
    MicE(AprsMicE),
    Unknown(Vec<u8>)
}

struct AprsDataWithDestination {
    Position(AprsPosition),
    Message(AprsMessage),
    Unknown(Vec<u8>)
}
```

---

I don't know much about APRS myself, so you and other users of the library are in a better position to decide how to weigh these tradeoffs.

**Comment by scd31** [comment]
@Benjamin-L That's a good point. ~~I think that's probably a more robust way to do this - it's a bit more complicated but I think it's worth it~~ I need to think about this some more. The drawbacks aren't that major for most APRS use-cases I think and the simpler API would be nice

**Comment by scd31** [comment]
> The other minor disadvantage is that there's no way to represent unknown data without a position(destination?) specified.

I believe that all unknown data has a destination. Mic-E technically has a destination, it's just overloaded (i.e. when you see it's a Mic-E packet you interpret the destination bits differently). So for unknown I think it would have to have a destination, since you wouldn't know how to interpret the destination differently if required

**Comment by scd31** [comment]
I haven't had time to implement this but I'm planning to do it soon.

With my new knowledge of APRS, I believe the first proposed method is the best. The destination field (almost?) never has a specific destination - instead, it seems to be used for holding data about the program sending the packets. For instance, Direwolf 1.6 will use `APDW16` as its destination. AprsMessages which are destined to a specific user have an entirely separate destination field which is used instead.

**Comment by scd31** [comment]
> It is possible to include a standard APRS-formatted position in the Mic-E
status text field. A suitable position will cause the APRS display software to
override any position data the Mic-E has encoded. This is useful if using a
Mic-E without a GPS receiver.

This is from the APRS spec. I won't be implementing this in my initial PR but may add it in the future if it turns out to be needed.
